### ISSUE TITLE
Some possible errors.

### ISSUE THREAD

**Issue by Tygrain** [RblSb/SyncTubeApp#4]
I think there are some possible errors in [this](https://github.com/RblSb/SyncTubeApp/blob/1daedfe08e0fcd3f280d5208248c33da814df3c0/lib/app.dart) code.

- The setState method is not called anywhere in the _AppState widget, which means if there is a state change, the widget tree will not rebuild.

- The orientationListener subscription is not cancelled when the widget is disposed, which could lead to a memory leak.

- The NativeDeviceOrientationCommunicator and orientationStream are deprecated and should be replaced with the DeviceOrientation package.

- The removeFocus function is not implemented and will cause an error if called.

- The SystemChrome.setPreferredOrientations method is not called when the device is in a portrait orientation. This could lead to the app not locking to the landscape orientation.

- The floatingActionButton is not implemented correctly. It should be a child of the Scaffold widget, not a property.

- The onWillPop function is not implemented, which means it will always return true, and the app will exit whenever the user taps the back button.

**Comment by RblSb** [comment]
- There is no state in `App`, state is keeped in `AppModel`, binded with `ChangeNotifierProvider.value(value: app)` and updated when `notifyListeners()` is called in `AppModel`
- There is `orientationListener?.cancel()` in `App.dispose()`
- I updated deps and don't see any deprecations in code, docs or github repo of this library, what do you mean?
- There is `void removeFocus()` in `app.dart`
- There is no `portrait mode`, only `auto` and `locked both sides landscape` currently
- It should not, there is `floatingActionButton` field in `Scaffold`
- Are you talking about Latest Servers page? Do you think minimizing instead of exiting will be better here?
