### ISSUE TITLE
Stuck at "Connection..." when joining a room

### ISSUE THREAD

**Issue by cheez95** [RblSb/SyncTubeApp#6]
Hello, I encountered an issue where the app stuck in making a connection when joining a room.
I've switched between Wi-Fi and cellular networks but have had no avail. I'm located in Taiwan. 

[Screenshot_2024-02-25-03-01-26-38_77254a6c584855962279a82525336fc6](https://github.com/RblSb/SyncTubeApp/assets/72521605/f2511875-460b-4785-be73-9c213c1ee539)

**Comment by RblSb** [comment]
Do you mean connecting to https://synctube.onrender.com?
This demo takes about 30 seconds to first load the page due to the nature of this hosting.

If you mean your personal server, which works via browser, but does not open after adding it url to app, I will need to find out your url to debug how it works for me.

**Comment by cheez95** [comment]
It's about the personal room/server. I had no problem connecting to that default server; it only took a second to connect.

> If you mean your personal server, which works via browser, but does not open after adding it url to app, I will need to find out your url to debug how it works for me.

Yes, that is the case. I have created another room for testing out, room #1178. URL as below:
https://sync-tube.de/room/_RLYCTe4

**Comment by RblSb** [comment]
Sorry for confusion, this is app for another synctube service, where you need to host server page by yourself and then connect with this app. Not related to sync-tube.de
